### ISSUE TITLE
API usability

### ISSUE THREAD

**Issue by miguel-vila** [zio/zio-metrics#52]
Hi, first of all thanks for this library. 

I'm using it at the moment but I noticed the API is kind of strange, requiring a `Queue[Metric]` to be passed every time a metric needs to be reported. An important issue is that nothing prevents a user of passing a different instance than the one that was used during the `.listen` call so I'm wondering if this is something that can be improved. I don't have a concrete suggestion, unfortunately, but feels creating the queue and listening are setup steps that could be encapsulated.

**Comment by toxicafunk** [comment]
Ok, so:
1. yes, I agree this can be improved for the whole StatsD/DogstatsD experience. Notice from https://github.com/zio/zio-metrics/blob/master/statsd/src/test/scala/zio/metrics/StatsDClientTest.scala that you can mitigate this (make it look nicer) using implicit parameters:

```scala
  val rt = Runtime.unsafeFromLayer(Encoder.statsd ++ Console.live ++ Clock.live)
  val client = StatsDClient()

  def program(r: Long)(implicit queue: Queue[Metric]) =
    for {
      clock <- RIO.environment[Clock]
      _     <- client.listen
      t1    <- clock.get.currentTime(TimeUnit.MILLISECONDS)
      _     <- client.increment("zmetrics.counter", 0.9)
      _     <- putStrLn(s"waiting for $r s") *> clock.get.sleep(Duration(r, TimeUnit.SECONDS))
      t2    <- clock.get.currentTime(TimeUnit.MILLISECONDS)
      _     <- client.timer("zmetrics.timer", (t2 - t1).toDouble, 0.9)
    } yield ()
```
2. This gave me the idea that the simplest way to improve the API is by creating `ZLayer`s for StatsD/DogStatsD that manipulate their own `Queue` internally (make it private so that no one outside the layer can access it). Then we can simply provide the layers, each with its own internal `Queue`, so that a user can't pass arbitrary Queues to it and no users need to worry about this implementation detail.

Wdyt @miguel-vila? Wanna give it a go? I'd be happy to give more details if needed.

**Comment by miguel-vila** [comment]
👋 , @toxicafunk , I opened a PR with some initial code changes, still not there, tho.

**Comment by toxicafunk** [comment]
Addresed on https://github.com/zio/zio-metrics/pull/53
